Controllers/HomeOwnersController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using HomeOwnersApp.Data;
using HomeOwnersApp.Models;
using Microsoft.AspNetCore.Authorization;

namespace HomeOwnersApp.Controllers
{
    [Authorize]
    public class HomeOwnersController : Controller
    {
        private readonly AppDataContext _context;

        public HomeOwnersController(AppDataContext context)
        {
            _context = context;
        }

        // GET: HomeOwners
        public async Task<IActionResult> Index()
        {
              return _context.HomeOwners != null ? 
                          View(await _context.HomeOwners.ToListAsync()) :
                          Problem("Entity set 'AppDataContext.HomeOwners'  is null.");
        }

        // GET: HomeOwners/Details/5
        public async Task<IActionResult> Details(Guid? id)
        {
            if (id == null || _context.HomeOwners == null)
            {
                return NotFound();
            }

            var homeOwners = await _context.HomeOwners
                .FirstOrDefaultAsync(m => m.Id == id);
            if (homeOwners == null)
            {
                return NotFound();
            }

            return View(homeOwners);
        }

        // GET: HomeOwners/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: HomeOwners/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Name,PhoneNumber,Age,Site")] HomeOwners homeOwners)
        {
            if (ModelState.IsValid)
            {
                homeOwners.Id = Guid.NewGuid();
                _context.Add(homeOwners);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(homeOwners);
        }

        // GET: HomeOwners/Edit/5
        public async Task<IActionResult> Edit(Guid? id)
        {
            if (id == null || _context.HomeOwners == null)
            {
                return NotFound();
            }

            var homeOwners = await _context.HomeOwners.FindAsync(id);
            if (homeOwners == null)
            {
                return NotFound();
            }
            return View(homeOwners);
        }

        // POST: HomeOwners/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(Guid id, [Bind("Id,Name,PhoneNumber,Age,Site")] HomeOwners homeOwners)
        {
            if (id != homeOwners.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(homeOwners);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!HomeOwnersExists(homeOwners.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(homeOwners);
        }

        // GET: HomeOwners/Delete/5
        public async Task<IActionResult> Delete(Guid? id)
        {
            if (_context.HomeOwners == null)
            {
                return Problem("Entity set 'AppDataContext.HomeOwners'  is null.");
            }
            var homeOwners = await _context.HomeOwners.FindAsync(id);
            if (homeOwners != null)
            {
                _context.HomeOwners.Remove(homeOwners);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool HomeOwnersExists(Guid id)
        {
          return (_context.HomeOwners?.Any(e => e.Id == id)).GetValueOrDefault();
        }
    }
}

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"]</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/font-awesome/css/all.min.css" />
    <link rel="stylesheet" href="~/datatables/css/jquery.dataTables.min.css" />
    <link rel="stylesheet" href="~/HomeOwnersApp.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Roboto:wght@300;400;700&display=swap">
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-dark bg-dark border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="HomeOwners" asp-action="Index"><i class="fa-solid fa-house-user me-2"></i>Gerenciador de Moradores</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <partial name="_LoginPartial.cshtml" />
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container text-center">
            &copy; 2023 - Genes Luna. All rights reserved.
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="~/datatables/js/jquery.dataTables.min.js"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>